### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#12]
There should be support for named sessions (session: URLs for all tabs and their tab-history).

User interface:

* Argument `-s/--save` to `:quit` (aliased to `:wq`) which saves as the default session.
* Optional argument to save under a session name.
* Commandline argument to select a session.

Ideally we'd like to save session files in a good plain text format, but unfortunately Qt makes this very hard - [QWebHistory](http://qt-project.org/doc/qt-5/qwebhistory.html) only has binary serialisation (with `<<`/`>>`), but no way to *load* history from plain text. There was a patch against QtWebKit which added functionality to do that, but it was rejected by upstream because "the binary format should suffice".

Other ideas to work around the binary format:

* Use python's struct module to read the binary format - this is rather fragile though, and looking at the Qt sources it seems rather complicated.
* Reimplement the history ourselves - this probably has its own problems, as it'll be rather hard to catch all link navigations (e.g. via javascript). [QWebHistoryInterface](http://qt-project.org/doc/qt-5/qwebhistoryinterface.html) also won't help because that's global, not per tab.

Maybe some other browser has some approach I didn't consider yet?

**Comment by The-Compiler** [comment]
Prototype of a session file:

```yaml
windows:
    - geometry: ...
      tabs:
          - zoom: 1.0
            position: 0
            history:
                - title: Github
                  url: http://www.github.com/
                - title: qutebrowser
                  url: http://www.github.com/
          - zoom: 0.8
            position: 0
            history:
                - title: heise
                  url: http://www.heise.de/
    - geometry: ...
      tabs:
          - zoom: 0.8
            position: 0
            history:
                - title: heise
                  url: http://www.heise.de/
```

**Comment by isene** [comment]
Now this looks clean and efficient.

-- 
		       "Tror du på virkeligheten?"
				   (Jonatan, 5 år)

Geir Isene                 |    /"\    ASCII Ribbon Campaign     
http://isene.com           |    \ /    Respect for open standards
http://isene.me            |     X     No HTML/RTF in email      
+47-4550 2470              |    / \    No MS Word docs in email

**Comment by The-Compiler** [comment]
There's some progress in the [sessions branch](https://github.com/The-Compiler/qutebrowser/tree/sessions). Basic saving/loading seems to work fine here. I still want to improve some stuff, but I'm quite certain this will finally be merged in the next days :)

That's how a session file looks:

```yaml
windows:
- geometry: !!binary |
    AdnQywABAAAAAAUAAAACHAAAB38AAAQ3AAAFAgAAAh4AAAd9AAAENQAAAAEAAA==
  tabs:
  - history:
    - title: DuckDuckGo
      url: https://duckduckgo.com/
    - title: The-Compiler/qutebrowser
      url: https://github.com/The-Compiler/qutebrowser
    - title: The-Compiler/qutebrowser at sessions
      url: https://github.com/The-Compiler/qutebrowser/tree/sessions
    - active: true
      title: Issues · The-Compiler/qutebrowser
      url: https://github.com/The-Compiler/qutebrowser/issues
    scroll-pos:
      x: 0
      y: 0
    zoom: 1.0
  - history:
    - title: Oops, you've found a dead link — Bitbucket
      url: https://bitbucket.org/porti/dwb
    - active: true
      title: portix / dwb — Bitbucket
      url: https://bitbucket.org/portix/dwb
    scroll-pos:
      x: 0
      y: 0
    zoom: 1.0
- geometry: !!binary |
    AdnQywABAAAAAAeAAAACHAAACf8AAAQ3AAAHggAAAh4AAAn9AAAENQAAAAEAAA==
  tabs:
  - history:
    - title: ''
      url: https://duckduckgo.com/?q=luakit&ia=about
    - title: Luakit Browser Framework
      url: https://mason-larobina.github.io/luakit/
    - title: The-Compiler/qutebrowser
      url: https://github.com/The-Compiler/qutebrowser
    - title: Issues · The-Compiler/qutebrowser
      url: https://github.com/The-Compiler/qutebrowser/issues
    - title: Issues · The-Compiler/qutebrowser
      url: https://github.com/The-Compiler/qutebrowser/issues?q=is%3Aissue+is%3Aopen+sessions
    - active: true
      title: 'Sessions · Issue #12 · The-Compiler/qutebrowser'
      url: https://github.com/The-Compiler/qutebrowser/issues/12
    scroll-pos:
      x: 0
      y: 2027
    zoom: 1.0
```
