### ISSUE TITLE
Sessions don't store titles correctly

### ISSUE THREAD

**Issue by EliteTK** [The-Compiler/qutebrowser#879]
With a default, out of the box, qutebrowser, with general:save-session set to true, do the following:

```
:open -t this
:open -t is
:open -t a
:open -t test
:quit
```

The session file produced will be as follows:
```yml
windows:
- active: true
  geometry: !!binary |
    AdnQywACAAAAAAAAAAAAAAAABVUAAALqAAAAAAAAAAAAAAVVAAAC6gAAAAAAAAAABVY=
  tabs:
  - history:
    - active: true
      original-url: https://www.duckduckgo.com/
      scroll-pos:
        x: 0
        y: 0
      title: DuckDuckGo
      url: https://duckduckgo.com/
      zoom: 1.0
  - history:
    - active: true
      original-url: https://duckduckgo.com/?q=this
      scroll-pos:
        x: 0
        y: 0
      title: ''
      url: https://duckduckgo.com/?q=this&ia=about
      zoom: 1.0
  - history:
    - active: true
      original-url: https://duckduckgo.com/?q=is
      scroll-pos:
        x: 0
        y: 0
      title: ''
      url: https://duckduckgo.com/?q=is&ia=meanings
      zoom: 1.0
  - history:
    - active: true
      original-url: https://duckduckgo.com/?q=a
      scroll-pos:
        x: 0
        y: 0
      title: ''
      url: https://duckduckgo.com/?q=a&ia=meanings
      zoom: 1.0
  - active: true
    history:
    - active: true
      original-url: https://duckduckgo.com/?q=test
      scroll-pos:
        x: 0
        y: 0
      title: ''
      url: https://duckduckgo.com/?q=test&ia=meanings
      zoom: 1.0
```

As can be seen, only the first initial tab has a title stored.

This is possibly for the same reason that #786 is not a simple fix.
