### ISSUE TITLE
Merge quickmarks and bookmarks?

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#882]
See #840 - the difference between quickmarks and bookmarks also is confusing for users sometimes, so it might make sense to merge them into one. Basically, simply having *bookmarks* with an optional name/label, and when that is set, they're "quickmarks".

**Comment by sdoubleyou** [comment]
Please do not :-) QuickMarks go well with more character like DWB. B + QM = very fast. Bookmarks has the problem that it can not be searched. that's the only issues. The also do not need a shortcut. I think, the division as vimperator or dactyl is a good approach

**Comment by lamarpavel** [comment]
@sdoubleyou I don't understand the problem, if bookmarks and quickmarks would be merged, then the resulting marks would be searchable __and__ could optionally have a keyword just like a quickmark. You wouldn't lose anything.

**Comment by The-Compiler** [comment]
Just as @lamarpavel said, this is mainly about the way marks are stored on disk - I intend the user-interface to stay the same more or less, except of `:open` optionally also opening marks as explained in #840.

What I'm a bit worried about is that the format most likely has to change, as I'm not 100% happy with the directory format I [proposed for bookmarks](https://github.com/The-Compiler/qutebrowser/pull/681#issuecomment-104715505), and the `<label> <url>` (quickmarks) and `<url> <title>` formats are far too inflexible to add new information...

What about using yaml, just like the session files? This would mean something like this:

```yml
- url: http://www.qutebrowser.org/
  title: qutebrowser
  label: git
- url: http://www.example.org/
  title: Example Page
...
```

And could also be easily changed to allow subfolders later:

```yml
- projects:
  - url: http://www.qutebrowser.org/
    title: qutebrowser
    label: git
  - url: http://www.herbstluftwm.org/
    title: herbstluftwm
- url: http://www.example.org/
  title: Example Page
...
```

However, it clearly loses the "very easy to write by hand, modify by a shell script, etc." property of the old format...

@Emdek also proposed using [xbel](https://en.wikipedia.org/wiki/XBEL) which is a standard format for bookmarks, but meh... it's XML :wink:

What do you think?
